SchoolApp/Models/Course.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace SchoolApp.Models
{
    public class Course
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Key]
        public int CourseId { get; set; }

        [Required]
        [StringLength(50)]
        public string CourseName { get; set; }
        

        public int TeacherId { get; set; }
        public Teacher Teacher { get; set; }
       
        public List<Assignment> Assignments { get; set; }

        public List<Student> Students { get; set; }
    }
}

SchoolApp/ViewModels/AddCourseViewModel.cs
using SchoolApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SchoolApp.ViewModels
{
    public class AddCourseViewModel
    {
        public Course course { get; set; }
        public IEnumerable<Teacher> Teachers { get; set; }
        
    }
}

SchoolApp/ViewModels/CourseViewModel.cs
using SchoolApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SchoolApp.ViewModels
{
    public class CourseViewModel
    {
        public Course GetCourse { get; set; }
        public Teacher GetTeacher { get; set; }
        public IEnumerable<Assignment> Assignments { get; set; }
       

    }
}

SchoolApp/Controllers/AssignmentController.cs
using Microsoft.AspNetCore.Mvc;
using SchoolApp.Models;
using SchoolApp.ViewModels;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace SchoolApp.Controllers
{
    public class AssignmentController : Controller
    {
        private readonly IAssignmentRepository _assignmentRepository;
        public AssignmentController(IAssignmentRepository assignmentRepository)
        {
            _assignmentRepository = assignmentRepository;

        }
        [HttpGet]
        public IActionResult AddAssignment(int CourseId)
        {
            Debug.WriteLine(CourseId);
            return View(new Assignment
            {
                CourseId = CourseId
            });
        }

        [HttpPost]
        public IActionResult AddAssignment(Assignment assignment)
        {
            _assignmentRepository.AddAssignment(assignment);
            return RedirectToAction("DisplayCourse","Course", new { CourseId = assignment.CourseId});
        }
    }
}

SchoolApp/Controllers/CourseController.cs
using Microsoft.AspNetCore.Mvc;
using SchoolApp.Models;
using SchoolApp.ViewModels;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Dynamic;
using System.Linq;
using System.Threading.Tasks;

namespace SchoolApp.Controllers
{
    public class CourseController : Controller
    {
        private readonly ICourseRepository _courseRepository;
        private readonly ITeacherRepository _teacherRepository;
        private readonly IAssignmentRepository _assignmentRepository;
        private readonly IStudentRepository _studentRepository;


        public CourseController(ICourseRepository courseRepository, ITeacherRepository teacherRepository, IAssignmentRepository assignmentRepository, IStudentRepository studentRepository)
        {
            _teacherRepository = teacherRepository;
            _courseRepository = courseRepository;
            _assignmentRepository = assignmentRepository;
            _studentRepository = studentRepository;
        }

        public ViewResult CourseList()
        {
            IEnumerable<Course> allCourses;

            allCourses = _courseRepository.AllCourses.OrderBy(c => c.CourseName);

            return View(allCourses);
        }


        public IActionResult DisplayCourse(int CourseId)
        {
            var course = _courseRepository.GetCourseById(CourseId);

            if (course == null)
            {
                return NotFound();
            }

            return View(new CourseViewModel
            {
                GetCourse = course,
                GetTeacher = _teacherRepository.GetTeacherById(course.TeacherId),
                Assignments = _assignmentRepository.GetAssignmentsByCourse(course.CourseId)
            });
        }


        [HttpGet]
        public IActionResult AddCourse()
        {
            
            return View(new AddCourseViewModel
            {
                course = null,
                Teachers = _teacherRepository.AllTeachers
            });
        }
        [HttpPost]
        public IActionResult AddCourse(AddCourseViewModel courseListView)
        {

            _courseRepository.AddCourse(courseListView.course);

            return RedirectToAction("CourseList");
        }

        [HttpGet]
        public IActionResult AddStudentsToCourse(int courseId)
        {

            return View(new StudentToCourse
            {
                Students = _studentRepository.AllStudents,
                courseId = courseId
            }) ;
        }
        [HttpPost]
        public IActionResult AddStudentsToCourse(int courseId, int[] StudentId)       
        {
            IList<Student> students = new List<Student>();
            foreach (var Id in StudentId)
            {
                students.Add(_studentRepository.GetStudentById(Id));
            }
            _courseRepository.AddStudentsToCourse(courseId, students);
            return RedirectToAction("DisplayCourse", "Course", new{CourseId = courseId});
            
        }

    }
}

SchoolApp/Views/Course/AddCourse.cshtml
@model AddCourseViewModel

<div class="d-flex justify-content-center" id="container">
    <div class="wrapper">
        <div>
            <a asp-controller="Course" asp-action="CourseList">&larr;Back</a><br />
            <form action="" method="post" class="form-horizontal" role="form">
                <h4>Please enter course name and pick a teacher.</h4>


                <div class="form-group">
                    <label asp-for="course.CourseName" class="control-label"></label>
                    <div class="">
                        <input type="text" id="course" asp-for="course.CourseName" class="form-control" autofocus required />
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="course.TeacherId" class="control-label"></label>
                    <div class="">
                        <select type="text" id="teacher" asp-for="course.TeacherId" class="form-control" required>

                            <option value=""></option>
                            @foreach (var teacher in Model.Teachers)
                            {
                                <option value="@teacher.Id">@teacher.FullName</option>
                            }
                        </select>
                    </div>
                </div>
                <div class="form-group">

                    <div class="form-row">
                        <div class="col-md-offset-2 ">
                            <input asp-action="AddCourse" type="submit" name="submitButton" class="btn btn-primary" value="Add" />
                        </div>

                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

SchoolApp/Views/Course/AddStudentsToCourse.cshtml
@model StudentToCourse

<div class="d-flex justify-content-center" id="container">
    <div class="wrapper">
        <div>
            <a asp-controller="Course" asp-action="DisplayCourse" asp-route-CourseId="@Model.courseId">&larr;Back</a><br />
            <form action="" method="post" class="form-horizontal" role="form">
                <h4>Add students to the course:</h4>
                <div>
                    <ul>
                        @foreach (var student in Model.Students)
                        {
                            <li>
                                <input type="checkbox" name="StudentId" value="@student.Id" />
                                @student.FullName
                            </li>
                         }
                    </ul>
                </div>
                <input asp-for="courseId" value="@Model.courseId" hidden />

                <div class="form-group">

                    <div class="form-row">
                        <div class="col-md-offset-2 ">
                            <input asp-action="AddStudentsToCourse" type="submit" name="submitButton" class="btn btn-primary" value="Add" />
                        </div>

                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

SchoolApp/Views/Course/CourseList.cshtml
@model IEnumerable<Course>

<div class="d-flex justify-content-center" id="container">
    <div class="wrapper">
        <table>
            <thead>
                <tr>
                    <td>
                        <h3>Courses:</h3>
                    </td>
                </tr>
            </thead>
            <tbody>
                @foreach (var course in Model)
                {
                    <tr>
                        <td>
                            <a asp-controller="Course" asp-action="DisplayCourse" asp-route-courseId="@course.CourseId">@course.CourseName</a>
                        </td>
                    </tr>
                }
                <tr>
                    <td>
                        <a asp-controller="Course" asp-action="AddCourse">+Add course</a>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

SchoolApp/Views/Course/DisplayCourse.cshtml
@model CourseViewModel

<div class="d-flex justify-content-center" id="container">
    <div class="wrapper">
        <div>
            <a asp-controller="Course" asp-action="CourseList">&larr;Back</a><br />
            <h2>@Model.GetCourse.CourseName</h2>
            <p>Teacher: @Model.GetTeacher.FullName</p>
            <p>
                <table class="assignmentList">
                    <thead>
                        <tr>
                            <td><h4>Assignments:</h4></td>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var assignment in Model.Assignments)
                        {
                            <tr>
                                <td>
                                    @assignment.Title
                                </td>
                                <td>
                                    @assignment.Description
                                </td>
                            </tr>
                        }
                        <tr>
                            <td>
                                <a asp-controller="Assignment" asp-action="AddAssignment" asp-route-CourseId="@Model.GetCourse.CourseId">+Add assignment</a>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </p>
            <p>
                <table>
                    <thead>
                        <tr>
                            <td><h4>Students:</h4></td>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var student in Model.GetCourse.Students)
                        {
                            <tr>
                                <td>
                                    @student.FullName
                                </td>

                            </tr>
                        }
                        <tr>
                            <td>
                                <a asp-controller="Course" asp-action="AddStudentsToCourse" asp-route-CourseId="@Model.GetCourse.CourseId">+Add students to course</a>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </p>
        </div>
    </div>
</div>